#!/bin/sh
#
# minio - SysV init script for MinIO Object Storage
#
# chkconfig: 2345 85 15
# description: MinIO High Performance Object Storage Server
# processname: minio
# pidfile: /var/run/minio.pid
# config: /etc/sysconfig/minio
#
### BEGIN INIT INFO
# Provides:          minio
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: MinIO Object Storage Server
# Description:       Starts and stops the MinIO object storage server.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

### CONFIG ###

NAME="minio"
DAEMON="/usr/local/bin/minio"

PIDFILE="/var/run/minio.pid"
LOCKFILE="/var/lock/subsys/minio"

CONFIG="/etc/sysconfig/minio"

[ -r "$CONFIG" ] && . "$CONFIG"


# Defaults
MINIO_VOLUMES=${MINIO_VOLUMES:-"/data"}
MINIO_OPTS=${MINIO_OPTS:-""}

RETVAL=0

start() {
    echo -n $"Starting $NAME: "

    [ -x "$DAEMON" ] || exit 5

    daemon \
        --pidfile="$PIDFILE" \
        "$DAEMON server $MINIO_OPTS $MINIO_VOLUMES >/dev/null 2>&1 & echo \$! > $PIDFILE"

    RETVAL=$?

    echo

    [ $RETVAL -eq 0 ] && touch "$LOCKFILE"

    return $RETVAL
}

stop() {
    echo -n $"Stopping $NAME: "

    killproc -p "$PIDFILE" "$DAEMON"

    RETVAL=$?

    echo

    [ $RETVAL -eq 0 ] && rm -f "$LOCKFILE" "$PIDFILE"

    return $RETVAL
}

restart() {
    stop
    start
}

reload() {
    restart
}

status() {
    status -p "$PIDFILE" "$DAEMON"
    RETVAL=$?
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        restart
        ;;
    reload)
        reload
        ;;
    status)
        status
        ;;
    condrestart|try-restart)
        [ -f "$LOCKFILE" ] && restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
        exit 2
esac

exit $RETVAL